version: '3.9'

services:
  sshserver:
    image: my_sshserver
    container_name: sshserver
    ports:
      - 2222:22
    environment:
      - sshuser=sshuser
      - password=pass
    volumes:
      - /home/minhho/ssh:/data
    deploy:
      replicas: 1